import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'EN' | 'FR' | 'DE';

const translations = {
  EN: {
    'nav.rent': 'Rent',
    'nav.buy': 'Buy',
    'nav.bnb': 'B&B',
    'nav.hotels': 'Hotels',
    'nav.hostels': 'Hostels',
    'nav.dashboard': 'Dashboard',
    'nav.list_property': 'List Property',
    'nav.signout': 'Sign Out',
    'nav.signin': 'Sign In',
    'nav.signup': 'Sign Up',
    'home.search_placeholder': 'Search locations',
    'home.verified_listings': 'Verified Listings',
    'home.verified_desc': 'Every property is vetted for authenticity.',
    'home.direct_connection': 'Direct Connection',
    'home.direct_desc': 'Connect directly with owners and buyers.',
    'home.property_management': 'Property Management',
    'home.property_desc': 'Tools for landlords to manage listings.',
    'home.secure_booking': 'Secure Booking',
    'home.secure_desc': 'Safe and secure rental process.',
    'home.bnb_hotels': 'B&B & Hotels',
    'home.bnb_hotels_desc': 'Unique accommodations, offices, and meeting spaces.',
    'home.view_bnbs': 'View B&Bs',
    'home.view_hotels': 'View Hotels',
    'home.explore_bnbs': 'Explore B&B Stays',
    'home.explore_hotels': 'Explore Hotels',
    'home.latest_rentals': 'Latest Rentals',
    'home.latest_rentals_desc': 'Discover top-rated rental properties available now.',
    'home.view_all': 'View All',
    'home.properties_for_sale': 'Properties For Sale',
    'home.properties_for_sale_desc': 'Find your dream home from verified sellers.',
    'search.placeholder': 'Search by location, city, or property name...',
    'search.near_me': 'Near Me (Active)',
    'search.use_location': 'Use Location',
    'search.near_me_btn': 'Near Me',
    'search.search_btn': 'Search',
    'search.filters': 'Filters',
    'search.reset_all': 'Reset All',
    'search.price_range': 'Price Range',
    'search.min': 'Min',
    'search.max': 'Max',
    'search.reset_price': 'Reset price',
    'search.bedrooms': 'Bedrooms',
    'search.amenities': 'Amenities',
    'search.properties_found': 'properties found',
    'search.loading': 'Loading...',
    'search.showing': 'Showing',
    'search.matching': 'matching',
    'search.price_lbl': 'price',
    'search.show_props': 'Show {n} properties',
    'search.list': 'List',
    'search.map': 'Map',
    'search.sort_featured': 'Featured',
    'search.sort_price_asc': 'Price: Low to High',
    'search.sort_price_desc': 'Price: High to Low',
    'search.sort_newest': 'Newest',
    'search.no_properties': 'No properties found',
    'search.try_adjusting': 'Try adjusting your filters or search query.',
    'search.clear_filters': 'Clear Filters',
    'cat.all_rentals': 'All Rentals',
    'cat.studio': 'Studio / Bedsitter',
    'cat.by_bedrooms': 'By Bedrooms',
    'cat.penthouse': 'Penthouse',
    'cat.own_compound': 'Own Compound',
    'cat.condominiums': 'Condominiums',
    'cat.business_spaces': 'Business Spaces',
    'cat.godowns': 'Godowns',
    'cat.stalls': 'Stalls',
    'cat.shops': 'Shops',
    'cat.rentals': 'Rentals',
    'cat.for_sale': 'For Sale',
    'cat.hotels': 'Hotels',
    'cat.hostels': 'Hostels',
    'cat.properties': 'Properties',
    'amenity.parking': 'Parking',
    'amenity.pool': 'Pool',
    'amenity.gym': 'Gym',
    'amenity.pet_friendly': 'Pet Friendly',
    'amenity.wifi': 'WiFi',
    'amenity.balcony': 'Balcony',
    'amenity.garden': 'Garden',
    'amenity.security': 'Security',
    'prop.for_rent': 'For Rent',
    'prop.for_sale': 'For Sale',
    'prop.hotel': 'Hotel',
    'prop.bnb': 'B&B',
    'prop.verified': 'Verified',
    'prop.reviews': 'reviews',
    'prop.mo': '/mo',
    'prop.bedrooms': 'Bedrooms',
    'prop.bathrooms': 'Bathrooms',
    'prop.sqft': 'Sq Ft',
    'prop.description': 'Description',
    'prop.amenities': 'Amenities',
    'prop.rate_stay': 'Rate your stay',
    'prop.rate_desc': 'How was your experience at this property?',
    'prop.you_rated': 'You rated this',
    'prop.stars': 'stars',
    'prop.location': 'Location',
    'prop.get_directions': 'Get Directions',
    'prop.book_to_see': 'Link Up to see exact location & directions',
    'prop.exact_unlocked': 'Exact Location Unlocked',
    'prop.exact_desc': 'You can now view the exact property pin on Google Maps to navigate.',
    'prop.open_maps': 'Open in Google Maps',
    'prop.hide_directions': 'Hide directions',
    'prop.book_to_reveal': 'Link Up to view owner contact details',
    'prop.request_tour': 'Link Up',
    'prop.book_now': 'Link Up',
    'prop.tour_requested': 'Linked Up!',
    'prop.booking_confirmed': 'Linked Up!',
    'prop.send_message': 'Send Message',
    'prop.chat_whatsapp': 'Chat on WhatsApp',
    'prop.ref_id': 'Reference ID:',
    'prop.listed_verified': 'Listed: Verified Listing',
    'prop.listed_unverified': 'Listed: Unverified',
    'prop.view_all_photos': 'View All Photos',
    'prop.dummy_desc': 'Experience the pinnacle of modern living in this stunning property. Featuring spacious interiors flooded with natural light, high-end finishes, and thoughtful design details throughout. The open-concept layout is perfect for entertaining, while private retreats offer serenity and comfort. Located in a prime neighborhood with easy access to amenities, schools, and transportation.',
    'dash.dashboard': 'Dashboard',
    'dash.my_profile': 'My Profile',
    'dash.profile': 'Profile',
    'dash.messages': 'Messages',
    'dash.bookings': 'Bookings',
    'dash.analytics': 'Analytics',
    'dash.subscription': 'Subscription',
    'dash.listings': 'My Listings',
    'dash.listings_short': 'Listings',
    'dash.reservations': 'Reservations',
    'dash.notifications': 'Notifications',
    'dash.all_properties': 'All Properties',
    'dash.properties': 'Properties',
    'dash.users': 'Users',
    'dash.subscriptions': 'Subscriptions',
    'dash.payments': 'Payments',
    'dash.sms_settings': 'SMS Settings',
    'dash.sms': 'SMS',
    'dash.sign_out': 'Sign Out',
    'dash.list_property': 'List Property',
    'dash.portal': 'PORTAL',
    'dash.welcome': 'Welcome back,',
    'dash.overview_sub': "Here's your {role} overview",
    'dash.analytics_title': 'Analytics & Reports',
    'dash.analytics_desc': 'View your performance metrics and download reports',
    'dash.no_data': 'No Data Available Yet',
    'dash.analytics_empty': 'Your analytics dashboard will populate with insights once your properties start receiving views, inquiries, and bookings.',
    'dash.download_report': 'Download Sample Report',
    'dash.inbox': 'Inbox',
    'dash.inbox_desc': 'Manage your communications',
    'dash.reservations_received': 'Reservations Received',
    'dash.reservations_received_desc': 'Bookings guests have made on your properties',
    'dash.loading_reservations': 'Loading reservations...',
    'dash.no_reservations': 'No reservations yet',
    'dash.no_reservations_desc': 'Bookings from guests will appear here once your listings receive reservations.',
    'dash.my_bookings': 'My Bookings',
    'dash.my_bookings_desc': 'Your property reservations',
    'dash.loading_bookings': 'Loading bookings...',
    'dash.no_bookings': 'No bookings yet',
    'dash.no_bookings_desc': 'Your bookings will appear here once you make a reservation.',
    'dash.browse_props': 'Browse Properties',
    'dash.total_listings': 'Total Listings',
    'dash.active_now': 'Active now',
    'dash.check_ins': 'Check-ins',
    'dash.no_upcoming_checkins': 'No upcoming check-ins',
    'dash.revenue': 'Revenue',
    'dash.from_confirmed': 'From confirmed bookings only',
    'dash.loading': 'Loading...',
    'dash.no_bookings_yet': 'No bookings yet',
    'dash.full_name': 'Full Name',
    'dash.email_address': 'Email Address',
    'dash.phone_number': 'Phone Number',
    'dash.verified': 'Verified',
    'dash.national_id': 'National ID or Passport',
    'dash.front_side': 'Front Side',
    'dash.back_side': 'Back Side',
    'dash.upload_front_hint': 'Upload the front of your ID / Passport',
    'dash.upload_back_hint': 'Upload the back of your ID / Passport',
    'dash.save_changes': 'Save Changes',
    'dash.saving': 'Saving...',
    'dash.id_desc': 'Upload clear photos of both sides of your National ID or Passport for identity verification.',
    'dash.phone_desc': 'Verified during registration. Contact support to change.',
    'dash.both_uploaded': 'Both sides uploaded — your identity is pending review.',
    'dash.upload_back_msg': 'Please also upload the back side to complete verification.',
    'dash.upload_front_msg': 'Please also upload the front side to complete verification.',
    'dash.guest_lbl': 'Guest:',
    'dash.unknown_property': 'Unknown Property',
    'dash.pending': 'Pending',
    'footer.platform': 'Platform',
    'footer.pricing': 'Pricing',
    'footer.support': 'Support & About',
    'footer.about': 'About Us',
    'footer.help': 'Help Center',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.contact': 'Contact Us',
    'footer.follow': 'Contact & Follow Us',
  },
  FR: {
    'nav.rent': 'Louer',
    'nav.buy': 'Acheter',
    'nav.bnb': 'Chambres d\'hôtes',
    'nav.hotels': 'Hôtels',
    'nav.hostels': 'Auberges',
    'nav.dashboard': 'Tableau de bord',
    'nav.list_property': 'Ajouter propriété',
    'nav.signout': 'Déconnexion',
    'nav.signin': 'Connexion',
    'nav.signup': 'S\'inscrire',
    'home.search_placeholder': 'Rechercher des lieux',
    'home.verified_listings': 'Annonces vérifiées',
    'home.verified_desc': 'Chaque propriété est vérifiée pour son authenticité.',
    'home.direct_connection': 'Connexion directe',
    'home.direct_desc': 'Connectez-vous directement avec les propriétaires et les acheteurs.',
    'home.property_management': 'Gestion immobilière',
    'home.property_desc': 'Outils pour les propriétaires pour gérer les annonces.',
    'home.secure_booking': 'Réservation sécurisée',
    'home.secure_desc': 'Processus de location sûr et sécurisé.',
    'home.bnb_hotels': 'Chambres d\'hôtes & Hôtels',
    'home.bnb_hotels_desc': 'Hébergements uniques, bureaux et espaces de réunion.',
    'home.view_bnbs': 'Voir Chambres d\'hôtes',
    'home.view_hotels': 'Voir Hôtels',
    'home.explore_bnbs': 'Explorer Chambres d\'hôtes',
    'home.explore_hotels': 'Explorer Hôtels',
    'home.latest_rentals': 'Dernières locations',
    'home.latest_rentals_desc': 'Découvrez les propriétés de location les mieux notées.',
    'home.view_all': 'Voir tout',
    'home.properties_for_sale': 'Propriétés à vendre',
    'home.properties_for_sale_desc': 'Trouvez la maison de vos rêves auprès de vendeurs vérifiés.',
    'search.placeholder': 'Recherche par lieu, ville ou nom...',
    'search.near_me': 'Près de moi (Actif)',
    'search.use_location': 'Localiser',
    'search.near_me_btn': 'Près de moi',
    'search.search_btn': 'Rechercher',
    'search.filters': 'Filtres',
    'search.reset_all': 'Tout réinitialiser',
    'search.price_range': 'Gamme de prix',
    'search.min': 'Min',
    'search.max': 'Max',
    'search.reset_price': 'Réinitialiser le prix',
    'search.bedrooms': 'Chambres',
    'search.amenities': 'Équipements',
    'search.properties_found': 'propriétés trouvées',
    'search.loading': 'Chargement...',
    'search.showing': 'Affichage',
    'search.matching': 'correspondant à',
    'search.price_lbl': 'prix',
    'search.show_props': 'Afficher {n} propriétés',
    'search.list': 'Liste',
    'search.map': 'Carte',
    'search.sort_featured': 'En vedette',
    'search.sort_price_asc': 'Prix : Croissant',
    'search.sort_price_desc': 'Prix : Décroissant',
    'search.sort_newest': 'Plus récent',
    'search.no_properties': 'Aucune propriété trouvée',
    'search.try_adjusting': 'Essayez d\'ajuster vos filtres ou votre recherche.',
    'search.clear_filters': 'Effacer les filtres',
    'cat.all_rentals': 'Toutes les locations',
    'cat.studio': 'Studio / Chambre',
    'cat.by_bedrooms': 'Par chambres',
    'cat.penthouse': 'Penthouse',
    'cat.own_compound': 'Propriété privée',
    'cat.condominiums': 'Condominiums',
    'cat.business_spaces': 'Espaces professionnels',
    'cat.godowns': 'Entrepôts',
    'cat.stalls': 'Stands',
    'cat.shops': 'Boutiques',
    'cat.rentals': 'Locations',
    'cat.for_sale': 'À vendre',
    'cat.hotels': 'Hôtels',
    'cat.hostels': 'Auberges',
    'cat.properties': 'Propriétés',
    'amenity.parking': 'Parking',
    'amenity.pool': 'Piscine',
    'amenity.gym': 'Salle de sport',
    'amenity.pet_friendly': 'Animaux acceptés',
    'amenity.wifi': 'WiFi',
    'amenity.balcony': 'Balcon',
    'amenity.garden': 'Jardin',
    'amenity.security': 'Sécurité',
    'prop.for_rent': 'A Louer',
    'prop.for_sale': 'A Vendre',
    'prop.hotel': 'Hôtel',
    'prop.bnb': 'B&B',
    'prop.verified': 'Vérifié',
    'prop.reviews': 'avis',
    'prop.mo': '/mois',
    'prop.bedrooms': 'Chambres',
    'prop.bathrooms': 'Salles de bain',
    'prop.sqft': 'Mètres Carrés',
    'prop.description': 'Description',
    'prop.amenities': 'Équipements',
    'prop.rate_stay': 'Évaluez votre séjour',
    'prop.rate_desc': 'Comment s\'est passée votre expérience dans cette propriété ?',
    'prop.you_rated': 'Vous avez évalué ceci',
    'prop.stars': 'étoiles',
    'prop.location': 'Emplacement',
    'prop.get_directions': 'Obtenir l\'itinéraire',
    'prop.book_to_see': 'Réservez pour voir l\'emplacement exact',
    'prop.exact_unlocked': 'Emplacement Exact Débloqué',
    'prop.exact_desc': 'Vous pouvez maintenant voir le pin exact sur Google Maps.',
    'prop.open_maps': 'Ouvrir dans Google Maps',
    'prop.hide_directions': 'Masquer l\'itinéraire',
    'prop.book_to_reveal': 'Réservez pour révéler les détails de contact',
    'prop.request_tour': 'Demander une visite',
    'prop.book_now': 'Réserver',
    'prop.tour_requested': 'Visite demandée',
    'prop.booking_confirmed': 'Réservation confirmée !',
    'prop.send_message': 'Envoyer un message',
    'prop.chat_whatsapp': 'Discuter sur WhatsApp',
    'prop.ref_id': 'Référence ID :',
    'prop.listed_verified': 'Annonce : Vérifiée',
    'prop.listed_unverified': 'Annonce : Non vérifiée',
    'prop.view_all_photos': 'Voir toutes les photos',
    'prop.dummy_desc': 'Découvrez le summum de la vie moderne dans cette magnifique propriété. Dotée d\'intérieurs spacieux inondés de lumière naturelle, de finitions haut de gamme et de détails de conception soignés. L\'aménagement à aire ouverte est parfait pour recevoir, tandis que les retraites privées offrent sérénité et confort. Située dans un quartier de choix avec un accès facile aux commodités, aux écoles et aux transports.',
    'dash.dashboard': 'Tableau de bord',
    'dash.my_profile': 'Mon profil',
    'dash.profile': 'Profil',
    'dash.messages': 'Messages',
    'dash.bookings': 'Réservations',
    'dash.analytics': 'Analytique',
    'dash.subscription': 'Abonnement',
    'dash.listings': 'Mes annonces',
    'dash.listings_short': 'Annonces',
    'dash.reservations': 'Réservations reçues',
    'dash.notifications': 'Notifications',
    'dash.all_properties': 'Toutes les propriétés',
    'dash.properties': 'Propriétés',
    'dash.users': 'Utilisateurs',
    'dash.subscriptions': 'Abonnements',
    'dash.payments': 'Paiements',
    'dash.sms_settings': 'Paramètres SMS',
    'dash.sms': 'SMS',
    'dash.sign_out': 'Déconnexion',
    'dash.list_property': 'Ajouter propriété',
    'dash.portal': 'PORTAIL',
    'dash.welcome': 'Bienvenue,',
    'dash.overview_sub': 'Voici votre aperçu {role}',
    'dash.analytics_title': 'Analytique & Rapports',
    'dash.analytics_desc': 'Consultez vos indicateurs de performance et téléchargez des rapports',
    'dash.no_data': 'Aucune donnée disponible',
    'dash.analytics_empty': 'Votre tableau de bord sera rempli d\'informations dès que vos propriétés commenceront à recevoir des vues, des demandes et des réservations.',
    'dash.download_report': 'Télécharger un rapport exemple',
    'dash.inbox': 'Boîte de réception',
    'dash.inbox_desc': 'Gérez vos communications',
    'dash.reservations_received': 'Réservations reçues',
    'dash.reservations_received_desc': 'Réservations faites par les clients sur vos propriétés',
    'dash.loading_reservations': 'Chargement des réservations...',
    'dash.no_reservations': 'Aucune réservation',
    'dash.no_reservations_desc': 'Les réservations des clients apparaîtront ici une fois vos annonces actives.',
    'dash.my_bookings': 'Mes réservations',
    'dash.my_bookings_desc': 'Vos réservations de propriétés',
    'dash.loading_bookings': 'Chargement des réservations...',
    'dash.no_bookings': 'Aucune réservation',
    'dash.no_bookings_desc': 'Vos réservations apparaîtront ici une fois que vous aurez effectué une réservation.',
    'dash.browse_props': 'Parcourir les propriétés',
    'dash.total_listings': 'Total des annonces',
    'dash.active_now': 'Actif maintenant',
    'dash.check_ins': 'Arrivées',
    'dash.no_upcoming_checkins': 'Aucune arrivée prévue',
    'dash.revenue': 'Revenus',
    'dash.from_confirmed': 'Des réservations confirmées uniquement',
    'dash.loading': 'Chargement...',
    'dash.no_bookings_yet': 'Aucune réservation',
    'dash.full_name': 'Nom complet',
    'dash.email_address': 'Adresse e-mail',
    'dash.phone_number': 'Numéro de téléphone',
    'dash.verified': 'Vérifié',
    'dash.national_id': 'Carte nationale ou Passeport',
    'dash.front_side': 'Côté recto',
    'dash.back_side': 'Côté verso',
    'dash.upload_front_hint': 'Téléchargez le recto de votre pièce d\'identité',
    'dash.upload_back_hint': 'Téléchargez le verso de votre pièce d\'identité',
    'dash.save_changes': 'Enregistrer',
    'dash.saving': 'Enregistrement...',
    'dash.id_desc': 'Téléchargez des photos claires des deux côtés de votre carte nationale ou passeport pour la vérification d\'identité.',
    'dash.phone_desc': 'Vérifié lors de l\'inscription. Contactez le support pour modifier.',
    'dash.both_uploaded': 'Les deux côtés téléchargés — votre identité est en cours de vérification.',
    'dash.upload_back_msg': 'Veuillez également télécharger le verso pour compléter la vérification.',
    'dash.upload_front_msg': 'Veuillez également télécharger le recto pour compléter la vérification.',
    'dash.guest_lbl': 'Client :',
    'dash.unknown_property': 'Propriété inconnue',
    'dash.pending': 'En attente',
    'footer.platform': 'Plateforme',
    'footer.pricing': 'Tarifs',
    'footer.support': 'Support & À propos',
    'footer.about': 'À propos de nous',
    'footer.help': 'Centre d\'aide',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.privacy': 'Politique de confidentialité',
    'footer.contact': 'Nous contacter',
    'footer.follow': 'Contact & Suivez-nous',
  },
  DE: {
    'nav.rent': 'Mieten',
    'nav.buy': 'Kaufen',
    'nav.bnb': 'B&B',
    'nav.hotels': 'Hotels',
    'nav.hostels': 'Hostels',
    'nav.dashboard': 'Dashboard',
    'nav.list_property': 'Immobilie einstellen',
    'nav.signout': 'Abmelden',
    'nav.signin': 'Anmelden',
    'nav.signup': 'Registrieren',
    'home.search_placeholder': 'Orte suchen',
    'home.verified_listings': 'Geprüfte Einträge',
    'home.verified_desc': 'Jede Immobilie wird auf Echtheit geprüft.',
    'home.direct_connection': 'Direkte Verbindung',
    'home.direct_desc': 'Verbinden Sie sich direkt mit Eigentümern und Käufern.',
    'home.property_management': 'Immobilienverwaltung',
    'home.property_desc': 'Tools für Vermieter zur Verwaltung von Einträgen.',
    'home.secure_booking': 'Sichere Buchung',
    'home.secure_desc': 'Sicherer und geschützter Mietprozess.',
    'home.bnb_hotels': 'B&B & Hotels',
    'home.bnb_hotels_desc': 'Einzigartige Unterkünfte, Büros und Tagungsräume.',
    'home.view_bnbs': 'B&Bs ansehen',
    'home.view_hotels': 'Hotels ansehen',
    'home.explore_bnbs': 'B&B Aufenthalte entdecken',
    'home.explore_hotels': 'Hotels entdecken',
    'home.latest_rentals': 'Neueste Vermietungen',
    'home.latest_rentals_desc': 'Entdecken Sie erstklassige Mietobjekte, die jetzt verfügbar sind.',
    'home.view_all': 'Alle ansehen',
    'home.properties_for_sale': 'Immobilien zum Verkauf',
    'home.properties_for_sale_desc': 'Finden Sie Ihr Traumhaus von geprüften Verkäufern.',
    'search.placeholder': 'Suche nach Ort, Stadt oder Name...',
    'search.near_me': 'In meiner Nähe (Aktiv)',
    'search.use_location': 'Standort nutzen',
    'search.near_me_btn': 'In meiner Nähe',
    'search.search_btn': 'Suchen',
    'search.filters': 'Filter',
    'search.reset_all': 'Alles zurücksetzen',
    'search.price_range': 'Preisklasse',
    'search.min': 'Min',
    'search.max': 'Max',
    'search.reset_price': 'Preis zurücksetzen',
    'search.bedrooms': 'Schlafzimmer',
    'search.amenities': 'Ausstattung',
    'search.properties_found': 'Immobilien gefunden',
    'search.loading': 'Laden...',
    'search.showing': 'Zeige',
    'search.matching': 'passend zu',
    'search.price_lbl': 'Preis',
    'search.show_props': '{n} Immobilien anzeigen',
    'search.list': 'Liste',
    'search.map': 'Karte',
    'search.sort_featured': 'Empfohlen',
    'search.sort_price_asc': 'Preis: Aufsteigend',
    'search.sort_price_desc': 'Preis: Absteigend',
    'search.sort_newest': 'Neueste',
    'search.no_properties': 'Keine Immobilien gefunden',
    'search.try_adjusting': 'Versuchen Sie, Ihre Filter oder Suche anzupassen.',
    'search.clear_filters': 'Filter löschen',
    'cat.all_rentals': 'Alle Mietobjekte',
    'cat.studio': 'Studio / Einzimmer',
    'cat.by_bedrooms': 'Nach Schlafzimmern',
    'cat.penthouse': 'Penthouse',
    'cat.own_compound': 'Eigenes Grundstück',
    'cat.condominiums': 'Eigentumswohnungen',
    'cat.business_spaces': 'Gewerbeflächen',
    'cat.godowns': 'Lagerhäuser',
    'cat.stalls': 'Stände',
    'cat.shops': 'Geschäfte',
    'cat.rentals': 'Mietobjekte',
    'cat.for_sale': 'Zu Verkaufen',
    'cat.hotels': 'Hotels',
    'cat.hostels': 'Hostels',
    'cat.properties': 'Immobilien',
    'amenity.parking': 'Parkplatz',
    'amenity.pool': 'Pool',
    'amenity.gym': 'Fitnessstudio',
    'amenity.pet_friendly': 'Haustiere erlaubt',
    'amenity.wifi': 'WLAN',
    'amenity.balcony': 'Balkon',
    'amenity.garden': 'Garten',
    'amenity.security': 'Sicherheit',
    'prop.for_rent': 'Zu Vermieten',
    'prop.for_sale': 'Zu Verkaufen',
    'prop.hotel': 'Hotel',
    'prop.bnb': 'B&B',
    'prop.verified': 'Verifiziert',
    'prop.reviews': 'Bewertungen',
    'prop.mo': '/Mo',
    'prop.bedrooms': 'Schlafzimmer',
    'prop.bathrooms': 'Badezimmer',
    'prop.sqft': 'Quadratmeter',
    'prop.description': 'Beschreibung',
    'prop.amenities': 'Ausstattung',
    'prop.rate_stay': 'Bewerten Sie Ihren Aufenthalt',
    'prop.rate_desc': 'Wie war Ihre Erfahrung in dieser Immobilie?',
    'prop.you_rated': 'Sie haben dies bewertet mit',
    'prop.stars': 'Sternen',
    'prop.location': 'Standort',
    'prop.get_directions': 'Route planen',
    'prop.book_to_see': 'Buchen Sie, um den genauen Standort zu sehen',
    'prop.exact_unlocked': 'Genauer Standort freigeschaltet',
    'prop.exact_desc': 'Sie können jetzt die genaue Nadel auf Google Maps sehen.',
    'prop.open_maps': 'In Google Maps öffnen',
    'prop.hide_directions': 'Route ausblenden',
    'prop.book_to_reveal': 'Buchen Sie, um Kontaktdaten anzuzeigen',
    'prop.request_tour': 'Besichtigung anfragen',
    'prop.book_now': 'Jetzt buchen',
    'prop.tour_requested': 'Besichtigung angefragt',
    'prop.booking_confirmed': 'Buchung bestätigt!',
    'prop.send_message': 'Nachricht senden',
    'prop.chat_whatsapp': 'Chat auf WhatsApp',
    'prop.ref_id': 'Referenz ID:',
    'prop.listed_verified': 'Gelistet: Verifiziert',
    'prop.listed_unverified': 'Gelistet: Nicht verifiziert',
    'prop.view_all_photos': 'Alle Fotos ansehen',
    'prop.dummy_desc': 'Erleben Sie den Höhepunkt des modernen Wohnens in dieser atemberaubenden Immobilie. Mit geräumigen, von natürlichem Licht durchfluteten Innenräumen, hochwertigen Oberflächen und durchdachten Designdetails. Das offene Layout eignet sich perfekt für Unterhaltung, während private Rückzugsorte Ruhe und Komfort bieten. In einer erstklassigen Nachbarschaft mit einfachem Zugang zu Annehmlichkeiten, Schulen und Verkehrsmitteln gelegen.',
    'dash.dashboard': 'Dashboard',
    'dash.my_profile': 'Mein Profil',
    'dash.profile': 'Profil',
    'dash.messages': 'Nachrichten',
    'dash.bookings': 'Buchungen',
    'dash.analytics': 'Analytik',
    'dash.subscription': 'Abonnement',
    'dash.listings': 'Meine Inserate',
    'dash.listings_short': 'Inserate',
    'dash.reservations': 'Reservierungen',
    'dash.notifications': 'Benachrichtigungen',
    'dash.all_properties': 'Alle Immobilien',
    'dash.properties': 'Immobilien',
    'dash.users': 'Nutzer',
    'dash.subscriptions': 'Abonnements',
    'dash.payments': 'Zahlungen',
    'dash.sms_settings': 'SMS-Einstellungen',
    'dash.sms': 'SMS',
    'dash.sign_out': 'Abmelden',
    'dash.list_property': 'Immobilie einstellen',
    'dash.portal': 'PORTAL',
    'dash.welcome': 'Willkommen,',
    'dash.overview_sub': 'Hier ist Ihre {role} Übersicht',
    'dash.analytics_title': 'Analytik & Berichte',
    'dash.analytics_desc': 'Leistungsmetriken anzeigen und Berichte herunterladen',
    'dash.no_data': 'Noch keine Daten verfügbar',
    'dash.analytics_empty': 'Ihr Analyse-Dashboard wird mit Erkenntnissen befüllt, sobald Ihre Immobilien Aufrufe, Anfragen und Buchungen erhalten.',
    'dash.download_report': 'Beispielbericht herunterladen',
    'dash.inbox': 'Posteingang',
    'dash.inbox_desc': 'Verwalten Sie Ihre Kommunikation',
    'dash.reservations_received': 'Erhaltene Reservierungen',
    'dash.reservations_received_desc': 'Buchungen von Gästen für Ihre Immobilien',
    'dash.loading_reservations': 'Reservierungen werden geladen...',
    'dash.no_reservations': 'Noch keine Reservierungen',
    'dash.no_reservations_desc': 'Buchungen von Gästen erscheinen hier, sobald Ihre Inserate Reservierungen erhalten.',
    'dash.my_bookings': 'Meine Buchungen',
    'dash.my_bookings_desc': 'Ihre Immobilienreservierungen',
    'dash.loading_bookings': 'Buchungen werden geladen...',
    'dash.no_bookings': 'Noch keine Buchungen',
    'dash.no_bookings_desc': 'Ihre Buchungen erscheinen hier, sobald Sie eine Reservierung vorgenommen haben.',
    'dash.browse_props': 'Immobilien durchsuchen',
    'dash.total_listings': 'Inserate gesamt',
    'dash.active_now': 'Aktuell aktiv',
    'dash.check_ins': 'Check-ins',
    'dash.no_upcoming_checkins': 'Keine bevorstehenden Check-ins',
    'dash.revenue': 'Einnahmen',
    'dash.from_confirmed': 'Nur aus bestätigten Buchungen',
    'dash.loading': 'Laden...',
    'dash.no_bookings_yet': 'Noch keine Buchungen',
    'dash.full_name': 'Vollständiger Name',
    'dash.email_address': 'E-Mail-Adresse',
    'dash.phone_number': 'Telefonnummer',
    'dash.verified': 'Verifiziert',
    'dash.national_id': 'Personalausweis oder Reisepass',
    'dash.front_side': 'Vorderseite',
    'dash.back_side': 'Rückseite',
    'dash.upload_front_hint': 'Laden Sie die Vorderseite Ihres Ausweises hoch',
    'dash.upload_back_hint': 'Laden Sie die Rückseite Ihres Ausweises hoch',
    'dash.save_changes': 'Änderungen speichern',
    'dash.saving': 'Speichern...',
    'dash.id_desc': 'Laden Sie klare Fotos beider Seiten Ihres Personalausweises oder Reisepasses zur Identitätsprüfung hoch.',
    'dash.phone_desc': 'Bei der Registrierung verifiziert. Kontaktieren Sie den Support zum Ändern.',
    'dash.both_uploaded': 'Beide Seiten hochgeladen — Ihre Identität wird überprüft.',
    'dash.upload_back_msg': 'Bitte laden Sie auch die Rückseite zur vollständigen Verifizierung hoch.',
    'dash.upload_front_msg': 'Bitte laden Sie auch die Vorderseite zur vollständigen Verifizierung hoch.',
    'dash.guest_lbl': 'Gast:',
    'dash.unknown_property': 'Unbekannte Immobilie',
    'dash.pending': 'Ausstehend',
    'footer.platform': 'Plattform',
    'footer.pricing': 'Preise',
    'footer.support': 'Support & Über uns',
    'footer.about': 'Über uns',
    'footer.help': 'Hilfe-Center',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.contact': 'Kontaktieren Sie uns',
    'footer.follow': 'Kontakt & Folgen Sie uns',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return ['EN', 'FR', 'DE'].includes(saved) ? saved : 'EN';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language]?.[key as keyof typeof translations['EN']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
