import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'EN' | 'FR' | 'DE';

const translations = {
  EN: {
    'nav.rent': 'Rent',
    'nav.buy': 'Buy',
    'nav.bnb': 'B&B',
    'nav.hotels': 'Hotels',
    'nav.hostels': 'Hostels',
    'nav.dashboard': 'Dashboard',
    'nav.list_property': 'List Property',
    'nav.signout': 'Sign Out',
    'nav.signin': 'Sign In',
    'nav.signup': 'Sign Up',
    'home.search_placeholder': 'Search locations',
    'home.verified_listings': 'Verified Listings',
    'home.verified_desc': 'Every property is vetted for authenticity.',
    'home.direct_connection': 'Direct Connection',
    'home.direct_desc': 'Connect directly with owners and buyers.',
    'home.property_management': 'Property Management',
    'home.property_desc': 'Tools for landlords to manage listings.',
    'home.secure_booking': 'Secure Booking',
    'home.secure_desc': 'Safe and secure rental process.',
    'home.bnb_hotels': 'B&B & Hotels',
    'home.bnb_hotels_desc': 'Unique accommodations, offices, and meeting spaces.',
    'home.view_bnbs': 'View B&Bs',
    'home.view_hotels': 'View Hotels',
    'home.explore_bnbs': 'Explore B&B Stays',
    'home.explore_hotels': 'Explore Hotels',
    'home.latest_rentals': 'Latest Rentals',
    'home.latest_rentals_desc': 'Discover top-rated rental properties available now.',
    'home.view_all': 'View All',
    'home.properties_for_sale': 'Properties For Sale',
    'home.properties_for_sale_desc': 'Find your dream home from verified sellers.',
    'search.placeholder': 'Search by location, city, or property name...',
    'search.near_me': 'Near Me (Active)',
    'search.use_location': 'Use My Location',
    'search.search_btn': 'Search',
    'search.filters': 'Filters',
    'search.reset_all': 'Reset All',
    'search.price_range': 'Price Range',
    'search.bedrooms': 'Bedrooms',
    'search.amenities': 'Amenities',
    'search.properties_found': 'Properties found',
    'search.showing_properties': 'Showing properties for',
    'search.matching': 'matching',
    'search.sort_featured': 'Sort by: Featured',
    'search.sort_price_asc': 'Price: Low to High',
    'search.sort_price_desc': 'Price: High to Low',
    'search.sort_newest': 'Newest',
    'search.no_properties': 'No properties found',
    'search.try_adjusting': 'Try adjusting your filters or search query.',
    'search.clear_filters': 'Clear all filters',
    'prop.for_rent': 'For Rent',
    'prop.for_sale': 'For Sale',
    'prop.hotel': 'Hotel',
    'prop.bnb': 'B&B',
    'prop.verified': 'Verified',
    'prop.reviews': 'reviews',
    'prop.mo': '/mo',
    'prop.bedrooms': 'Bedrooms',
    'prop.bathrooms': 'Bathrooms',
    'prop.sqft': 'Sq Ft',
    'prop.description': 'Description',
    'prop.amenities': 'Amenities',
    'prop.rate_stay': 'Rate your stay',
    'prop.rate_desc': 'How was your experience at this property?',
    'prop.you_rated': 'You rated this',
    'prop.stars': 'stars',
    'prop.location': 'Location',
    'prop.get_directions': 'Get Directions',
    'prop.book_to_see': 'Book to see exact location & directions',
    'prop.exact_unlocked': 'Exact Location Unlocked',
    'prop.exact_desc': 'You can now view the exact property pin on Google Maps to navigate.',
    'prop.open_maps': 'Open in Google Maps',
    'prop.hide_directions': 'Hide directions',
    'prop.book_to_reveal': 'Book to reveal host contact details',
    'prop.request_tour': 'Request Tour',
    'prop.book_now': 'Book Now',
    'prop.tour_requested': 'Tour Requested',
    'prop.booking_confirmed': 'Booking Confirmed!',
    'prop.send_message': 'Send Message',
    'prop.chat_whatsapp': 'Chat on WhatsApp',
    'prop.ref_id': 'Reference ID:',
    'prop.listed_verified': 'Listed: Verified Listing',
    'prop.listed_unverified': 'Listed: Unverified',
    'prop.view_all_photos': 'View All Photos',
    'prop.dummy_desc': 'Experience the pinnacle of modern living in this stunning property. Featuring spacious interiors flooded with natural light, high-end finishes, and thoughtful design details throughout. The open-concept layout is perfect for entertaining, while private retreats offer serenity and comfort. Located in a prime neighborhood with easy access to amenities, schools, and transportation.',
    'footer.platform': 'Platform',
    'footer.pricing': 'Pricing',
    'footer.support': 'Support & About',
    'footer.about': 'About Us',
    'footer.help': 'Help Center',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.contact': 'Contact Us',
    'footer.follow': 'Contact & Follow Us',
  },
  FR: {
    'nav.rent': 'Louer',
    'nav.buy': 'Acheter',
    'nav.bnb': 'Chambres d\'hôtes',
    'nav.hotels': 'Hôtels',
    'nav.hostels': 'Auberges',
    'nav.dashboard': 'Tableau de bord',
    'nav.list_property': 'Ajouter propriété',
    'nav.signout': 'Déconnexion',
    'nav.signin': 'Connexion',
    'nav.signup': 'S\'inscrire',
    'home.search_placeholder': 'Rechercher des lieux',
    'home.verified_listings': 'Annonces vérifiées',
    'home.verified_desc': 'Chaque propriété est vérifiée pour son authenticité.',
    'home.direct_connection': 'Connexion directe',
    'home.direct_desc': 'Connectez-vous directement avec les propriétaires et les acheteurs.',
    'home.property_management': 'Gestion immobilière',
    'home.property_desc': 'Outils pour les propriétaires pour gérer les annonces.',
    'home.secure_booking': 'Réservation sécurisée',
    'home.secure_desc': 'Processus de location sûr et sécurisé.',
    'home.bnb_hotels': 'Chambres d\'hôtes & Hôtels',
    'home.bnb_hotels_desc': 'Hébergements uniques, bureaux et espaces de réunion.',
    'home.view_bnbs': 'Voir Chambres d\'hôtes',
    'home.view_hotels': 'Voir Hôtels',
    'home.explore_bnbs': 'Explorer Chambres d\'hôtes',
    'home.explore_hotels': 'Explorer Hôtels',
    'home.latest_rentals': 'Dernières locations',
    'home.latest_rentals_desc': 'Découvrez les propriétés de location les mieux notées.',
    'home.view_all': 'Voir tout',
    'home.properties_for_sale': 'Propriétés à vendre',
    'home.properties_for_sale_desc': 'Trouvez la maison de vos rêves auprès de vendeurs vérifiés.',
    'search.placeholder': 'Recherche par lieu, ville ou nom...',
    'search.near_me': 'Près de moi (Actif)',
    'search.use_location': 'Utiliser ma position',
    'search.search_btn': 'Rechercher',
    'search.filters': 'Filtres',
    'search.reset_all': 'Tout réinitialiser',
    'search.price_range': 'Gamme de prix',
    'search.bedrooms': 'Chambres',
    'search.amenities': 'Équipements',
    'search.properties_found': 'Propriétés trouvées',
    'search.showing_properties': 'Affichage des propriétés pour',
    'search.matching': 'correspondant à',
    'search.sort_featured': 'Trier par : En vedette',
    'search.sort_price_asc': 'Prix : Croissant',
    'search.sort_price_desc': 'Prix : Décroissant',
    'search.sort_newest': 'Plus récent',
    'search.no_properties': 'Aucune propriété trouvée',
    'search.try_adjusting': 'Essayez d\'ajuster vos filtres ou votre recherche.',
    'search.clear_filters': 'Effacer tous les filtres',
    'prop.for_rent': 'A Louer',
    'prop.for_sale': 'A Vendre',
    'prop.hotel': 'Hôtel',
    'prop.bnb': 'B&B',
    'prop.verified': 'Vérifié',
    'prop.reviews': 'avis',
    'prop.mo': '/mois',
    'prop.bedrooms': 'Chambres',
    'prop.bathrooms': 'Salles de bain',
    'prop.sqft': 'Mètres Carrés',
    'prop.description': 'Description',
    'prop.amenities': 'Équipements',
    'prop.rate_stay': 'Évaluez votre séjour',
    'prop.rate_desc': 'Comment s\'est passée votre expérience dans cette propriété ?',
    'prop.you_rated': 'Vous avez évalué ceci',
    'prop.stars': 'étoiles',
    'prop.location': 'Emplacement',
    'prop.get_directions': 'Obtenir l\'itinéraire',
    'prop.book_to_see': 'Réservez pour voir l\'emplacement exact',
    'prop.exact_unlocked': 'Emplacement Exact Débloqué',
    'prop.exact_desc': 'Vous pouvez maintenant voir le pin exact sur Google Maps.',
    'prop.open_maps': 'Ouvrir dans Google Maps',
    'prop.hide_directions': 'Masquer l\'itinéraire',
    'prop.book_to_reveal': 'Réservez pour révéler les détails de contact',
    'prop.request_tour': 'Demander une visite',
    'prop.book_now': 'Réserver',
    'prop.tour_requested': 'Visite demandée',
    'prop.booking_confirmed': 'Réservation confirmée !',
    'prop.send_message': 'Envoyer un message',
    'prop.chat_whatsapp': 'Discuter sur WhatsApp',
    'prop.ref_id': 'Référence ID :',
    'prop.listed_verified': 'Annonce : Vérifiée',
    'prop.listed_unverified': 'Annonce : Non vérifiée',
    'prop.view_all_photos': 'Voir toutes les photos',
    'prop.dummy_desc': 'Découvrez le summum de la vie moderne dans cette magnifique propriété. Dotée d\'intérieurs spacieux inondés de lumière naturelle, de finitions haut de gamme et de détails de conception soignés. L\'aménagement à aire ouverte est parfait pour recevoir, tandis que les retraites privées offrent sérénité et confort. Située dans un quartier de choix avec un accès facile aux commodités, aux écoles et aux transports.',
    'footer.platform': 'Plateforme',
    'footer.pricing': 'Tarifs',
    'footer.support': 'Support & À propos',
    'footer.about': 'À propos de nous',
    'footer.help': 'Centre d\'aide',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.privacy': 'Politique de confidentialité',
    'footer.contact': 'Nous contacter',
    'footer.follow': 'Contact & Suivez-nous',
  },
  DE: {
    'nav.rent': 'Mieten',
    'nav.buy': 'Kaufen',
    'nav.bnb': 'B&B',
    'nav.hotels': 'Hotels',
    'nav.hostels': 'Hostels',
    'nav.dashboard': 'Dashboard',
    'nav.list_property': 'Immobilie einstellen',
    'nav.signout': 'Abmelden',
    'nav.signin': 'Anmelden',
    'nav.signup': 'Registrieren',
    'home.search_placeholder': 'Orte suchen',
    'home.verified_listings': 'Geprüfte Einträge',
    'home.verified_desc': 'Jede Immobilie wird auf Echtheit geprüft.',
    'home.direct_connection': 'Direkte Verbindung',
    'home.direct_desc': 'Verbinden Sie sich direkt mit Eigentümern und Käufern.',
    'home.property_management': 'Immobilienverwaltung',
    'home.property_desc': 'Tools für Vermieter zur Verwaltung von Einträgen.',
    'home.secure_booking': 'Sichere Buchung',
    'home.secure_desc': 'Sicherer und geschützter Mietprozess.',
    'home.bnb_hotels': 'B&B & Hotels',
    'home.bnb_hotels_desc': 'Einzigartige Unterkünfte, Büros und Tagungsräume.',
    'home.view_bnbs': 'B&Bs ansehen',
    'home.view_hotels': 'Hotels ansehen',
    'home.explore_bnbs': 'B&B Aufenthalte entdecken',
    'prop.dummy_desc': 'Erleben Sie den Höhepunkt des modernen Wohnens in dieser atemberaubenden Immobilie. Mit geräumigen, von natürlichem Licht durchfluteten Innenräumen, hochwertigen Oberflächen und durchdachten Designdetails. Das offene Layout eignet sich perfekt für Unterhaltung, während private Rückzugsorte Ruhe und Komfort bieten. In einer erstklassigen Nachbarschaft mit einfachem Zugang zu Annehmlichkeiten, Schulen und Verkehrsmitteln gelegen.',
    'footer.platform': 'Plattform',
    'footer.pricing': 'Preise',
    'footer.support': 'Support & Über uns',
    'footer.about': 'Über uns',
    'footer.help': 'Hilfe-Center',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.contact': 'Kontaktieren Sie uns',
    'footer.follow': 'Kontakt & Folgen Sie uns',
    'home.explore_hotels': 'Hotels entdecken',
    'home.latest_rentals': 'Neueste Vermietungen',
    'home.latest_rentals_desc': 'Entdecken Sie erstklassige Mietobjekte, die jetzt verfügbar sind.',
    'home.view_all': 'Alle ansehen',
    'home.properties_for_sale': 'Immobilien zum Verkauf',
    'home.properties_for_sale_desc': 'Finden Sie Ihr Traumhaus von geprüften Verkäufern.',
    'search.placeholder': 'Suche nach Ort, Stadt oder Name...',
    'search.near_me': 'In meiner Nähe (Aktiv)',
    'search.use_location': 'Meinen Standort verwenden',
    'search.search_btn': 'Suchen',
    'search.filters': 'Filter',
    'search.reset_all': 'Alles zurücksetzen',
    'search.price_range': 'Preisklasse',
    'search.bedrooms': 'Schlafzimmer',
    'search.amenities': 'Ausstattung',
    'search.properties_found': 'Immobilien gefunden',
    'search.showing_properties': 'Zeige Immobilien für',
    'search.matching': 'passend zu',
    'search.sort_featured': 'Sortieren nach: Empfohlen',
    'search.sort_price_asc': 'Preis: Aufsteigend',
    'search.sort_price_desc': 'Preis: Absteigend',
    'search.sort_newest': 'Neueste',
    'search.no_properties': 'Keine Immobilien gefunden',
    'search.try_adjusting': 'Versuchen Sie, Ihre Filter oder Suche anzupassen.',
    'search.clear_filters': 'Alle Filter löschen',
    'prop.for_rent': 'Zu Vermieten',
    'prop.for_sale': 'Zu Verkaufen',
    'prop.hotel': 'Hotel',
    'prop.bnb': 'B&B',
    'prop.verified': 'Verifiziert',
    'prop.reviews': 'Bewertungen',
    'prop.mo': '/Mo',
    'prop.bedrooms': 'Schlafzimmer',
    'prop.bathrooms': 'Badezimmer',
    'prop.sqft': 'Quadratmeter',
    'prop.description': 'Beschreibung',
    'prop.amenities': 'Ausstattung',
    'prop.rate_stay': 'Bewerten Sie Ihren Aufenthalt',
    'prop.rate_desc': 'Wie war Ihre Erfahrung in dieser Immobilie?',
    'prop.you_rated': 'Sie haben dies bewertet mit',
    'prop.stars': 'Sternen',
    'prop.location': 'Standort',
    'prop.get_directions': 'Route planen',
    'prop.book_to_see': 'Buchen Sie, um den genauen Standort zu sehen',
    'prop.exact_unlocked': 'Genauer Standort freigeschaltet',
    'prop.exact_desc': 'Sie können jetzt die genaue Nadel auf Google Maps sehen.',
    'prop.open_maps': 'In Google Maps öffnen',
    'prop.hide_directions': 'Route ausblenden',
    'prop.book_to_reveal': 'Buchen Sie, um Kontaktdaten anzuzeigen',
    'prop.request_tour': 'Besichtigung anfragen',
    'prop.book_now': 'Jetzt buchen',
    'prop.tour_requested': 'Besichtigung angefragt',
    'prop.booking_confirmed': 'Buchung bestätigt!',
    'prop.send_message': 'Nachricht senden',
    'prop.chat_whatsapp': 'Chat auf WhatsApp',
    'prop.ref_id': 'Referenz ID:',
    'prop.listed_verified': 'Gelistet: Verifiziert',
    'prop.listed_unverified': 'Gelistet: Nicht verifiziert',
    'prop.view_all_photos': 'Alle Fotos ansehen',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return ['EN', 'FR', 'DE'].includes(saved) ? saved : 'EN';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language]?.[key as keyof typeof translations['EN']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
